language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pep8
script:
  - pep8 rebulk
  - coverage run --source=rebulk setup.py test
  - python setup.py build
after_success:
  - coveralls
