language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
install:
  - pip install -r requirements.txt
  - pip install pytest>=2.7.3 --upgrade
  - pip install pylint
  - pip install coveralls
script:
  - if [ $TRAVIS_PYTHON_VERSION != 2.6 ] && [ $TRAVIS_PYTHON_VERSION != 3.5 ]; then pylint rebulk; fi
  - coverage run --source=rebulk setup.py test
  - python setup.py build
after_success:
  - coveralls
